# raikuran/commands/init.py

import typer
from pathlib import Path

app = typer.Typer(help="Initialize a new Python or AI/ML project structure.")

@app.command("project")
def init_project(
    name: str = typer.Option(..., "--name", "-n", help="Name of the project folder"),
    ml: bool = typer.Option(False, help="Include ML-oriented folders: models/, data/, notebooks/"),
):
    """
    Scaffold a new Python or ML project structure.
    Does NOT create a virtual environment (use `raikuran env create` for that).
    """

    project_path = Path(name)

    if project_path.exists():
        typer.echo("❌ A folder with this name already exists.")
        raise typer.Exit(1)

    typer.echo(f"📁 Creating project structure in: {project_path}")
    project_path.mkdir(parents=True)

    # Create subdirectories
    folders = ["src", "tests"]
    if ml:
        folders += ["models", "data", "notebooks"]

    for folder in folders:
        dir_path = project_path / folder
        dir_path.mkdir(parents=True, exist_ok=True)

    # Create default files
    (project_path / "README.md").write_text(f"# {name}\n\nGenerated by Raikuran CLI.")
    (project_path / ".gitignore").write_text("__pycache__/\n*.pyc\n.ipynb_checkpoints/\n.venv/\n")
    (project_path / "requirements.txt").touch()
    (project_path / "src" / "main.py").write_text("if __name__ == '__main__':\n    print('Hello from Raikuran project.')\n")

    typer.echo("✅ Project initialized successfully.")

